export const REQUEST_CATEGORY_START = "REQUEST_CATEGORY_START";
export const REQUEST_CATEGORY_FINISHED = "REQUEST_CATEGORY_FINISH";
export const REQUEST_CATEGORY_FAILED = "REQUEST_CATEGORY_FAILED";
export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_FINISHED = "ADD_CATEGORY_FINISH";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";
export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";
export const UPDATE_CATEGORY_FINISHED = "UPDATE_CATEGORY_FINISH";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";
export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_FINISHED = "DELETE_CATEGORY_FINISHED";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const REQUEST_PRODUCT_START = "REQUEST_PRODUCT_START";
export const REQUEST_PRODUCT_FINISHED = "REQUEST_PRODUCT_FINISHED";
export const REQUEST_PRODUCT_FAILED = "REQUEST_PRODUCT_FAILED";
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_FINISHED = "ADD_PRODUCT_FINISHED";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";
export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_FINISHED = "UPDATE_PRODUCT_FINISHED";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_FINISHED = "DELETE_PRODUCT_FINISHED";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const REQUEST_ORDER_START = "REQUEST_ORDER_START";
export const REQUEST_ORDER_FINISHED = "REQUEST_ORDER_FINISHED";
export const REQUEST_ORDER_FAILED = "REQUEST_ORDER_FAILED";
export const DEACTIVE_ORDER_START = "DEACTIVE_ORDER_START";
export const DEACTIVE_ORDER_FINISHED = "DEACTIVE_ORDER_FINISHED";
export const DEACTIVE_ORDER_FAILED = "DEACTIVE_ORDER_FAILED";
export const UPDATE_ORDER_START = "UPDATE_ORDER_START";
export const UPDATE_ORDER_FINISHED = "UPDATE_ORDER_FINISHED";
export const UPDATE_ORDER_FAILED = "UPDATE_ORDER_FAILED";

export const REQUEST_BRAND_START = "REQUEST_BRAND_START";
export const REQUEST_BRAND_FINISHED = "REQUEST_BRAND_FINISHED";
export const REQUEST_BRAND_FAILED = "REQUEST_BRAND_FAILED";
export const ADD_BRAND_START = "ADD_BRAND_START";
export const ADD_BRAND_FINISHED = "ADD_BRAND_FINISHED";
export const ADD_BRAND_FAILED = "ADD_BRAND_FAILED";
export const UPDATE_BRAND_START = "UPDATE_BRAND_START";
export const UPDATE_BRAND_FINISHED = "UPDATE_BRAND_FINISHED";
export const UPDATE_BRAND_FAILED = "UPDATE_BRAND_FAILED";
export const DELETE_BRAND_START = "DELETE_BRAND_START";
export const DELETE_BRAND_FINISHED = "DELETE_BRAND_FINISHED";
export const DELETE_BRAND_FAILED = "DELETE_BRAND_FAILED";

export const LOADING_USER_START = "LOADING_USER_START"
export const LOADING_USER_FINISHED = "LOADING_USER_FINISHED"
export const LOADING_USER_FAILED = "LOADING_USER_FAILED"

export const LOADING_APPLICATION_STATE_START = "LOADING_USER_START"
export const LOADING_APPLICATION_STATE_FINISHED = "LOADING_USER_FINISHED"
export const LOADING_APPLICATION_STATE_FAILED = "LOADING_USER_FAILED"
  
export const USER_EXPIRED = 'redux-oidc/USER_EXPIRED';
export const SILENT_RENEW_ERROR = 'redux-oidc/SILENT_RENEW_ERROR';
export const SESSION_TERMINATED = 'redux-oidc/SESSION_TERMINATED';
export const USER_EXPIRING = 'redux-oidc/USER_EXPIRING';
export const USER_FOUND = 'redux-oidc/USER_FOUND';
export const LOADING_USER = 'redux-oidc/LOADING_USER';
export const USER_SIGNED_OUT = 'redux-oidc/USER_SIGNED_OUT';
export const LOAD_USER_ERROR = 'redux-oidc/LOAD_USER_ERROR';